### ISSUE TITLE
No 'version' key in the manifest file

### ISSUE THREAD

**Issue by rewse** [yutoyazaki/hass-nature-remo#9]
Home Assistant 2021.4 has began to raise the following warning message.
Home Assistant 2021.4 から以下の警告が出るようになりました。

> WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'nature_remo'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'nature_remo'

This is one of the breaking changes which is mentioned at https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes .
これは https://www.home-assistant.io/blog/2021/04/07/release-20214/#breaking-changes で言及されている Breaking Changes の一つです。

**Comment by Chabiichi** [comment]
私はエンジニアではないので良くわかってないのですが、バージョンの記述を変更するだけではダメなんですかね？
ユーザー側でできることってあるんでしょうか？

**Comment by rewse** [comment]
ユーザー側でも修正は容易で、custom_components/nature_remo/manifest.json に1行追加するだけです。

**変更前**

```
{
  "domain": "nature_remo",
  "name": "Nature Remo",
  "documentation": "https://github.com/yutoyazaki/hass-nature-remo",
  "codeowners": [
    "@yutoyazaki"
  ]
}
```

**変更後**

```
{
  "domain": "nature_remo",
  "name": "Nature Remo",
  "version": "0.5",
  "documentation": "https://github.com/yutoyazaki/hass-nature-remo",
  "codeowners": [
    "@yutoyazaki"
  ]
}
```

**Comment by yutoyazaki** [comment]
That warning has been fixed in [v0.5](https://github.com/yutoyazaki/hass-nature-remo/releases/tag/v0.5). Please update to the latest version of this custom integration.
However, as @rewse mentioned, just replace `manifest.json` would be fine. (Other than that, nothing has changed.)
If you still see this warning, please reopen the issue.

その警告は[v0.5](https://github.com/yutoyazaki/hass-nature-remo/releases/tag/v0.5)で修正されました。カスタムインテグレーションを最新版にアップデートしてください。
@rewse さんが仰るように、`manifest.json`を置き換えるだけでも大丈夫です。(それ以外に変更はありません)
もし引き続き警告が出るようでしたら教えてください。
